sudo: required

env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch origin docker-tests
  - git worktree add tests origin/docker-tests

script:
  - ./tests/docker_tests.sh
