---
language: python

# Use the new container infrastructure
sudo: required

env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04
    - DISTRIBUTION: ubuntu
      VERSION: 18.04
    - DISTRIBUTION: debian
      VERSION: 9

#Enable docker support
services:
  - docker

install:
  # Install dependencies for Molecule test
  - python3 -m pip install ansible
  - python3 -m pip install pytest
  - python3 -m pip install netaddr
  - python3 -m pip install molecule
  - python3 -m pip install docker

  # Check ansible and molecule version
  - ansible --version
  - molecule --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - DISTRIBUTION=$DISTRIBUTION VERSION=$VERSION molecule test 

