# roles/bind/tasks/main.yml
---

# Initialise distribution-specific variables
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: httpd

- name: Check whether `bind_zone_master_server_ip` was set
  assert:
    that: bind_zone_master_server_ip is defined

- name: Install BIND
  package:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ bind_packages }}"
  tags: bind

- name: Create serial
  command: date +%y%m%d%H
  register: timestamp
  changed_when: false
  tags: bind

- include: master.yml
  when: bind_zone_master_server_ip in ansible_all_ipv4_addresses

- include: slave.yml
  when: bind_zone_master_server_ip not in ansible_all_ipv4_addresses

- name: Start BIND service
  service:
    name: named
    state: started
    enabled: yes
  tags: bind

