# roles/bind/tasks/master.yml
# Set up a BIND master server
---

- name: Main BIND config file (master)
  template:
    src: master_etc_named.conf.j2
    dest: "/etc/named.conf"
    owner: root
    backup: yes
    group: named
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: restart bind
  tags: bind
  register: namedout
  ignore_errors: yes

- debug: var=namedout

- name: Create forward lookup zone file
  template:
    src: bind_zone.j2
    dest: "/var/named/{{ bind_zone_name }}"
    backup: yes
    owner: root
    group: named
    mode: "0640"
    setype: named_zone_t
    validate: '/sbin/named-checkzone -d {{ bind_zone_name }} %s'
  notify: restart bind
  tags: bind

- name: Create reverse lookup zone file
  template:
    src: reverse_zone.j2
    dest: "/var/named/{{ item|reverse_lookup_zone }}"
    owner: root
    group: named
    mode: "0640"
    setype: named_zone_t
    validate: "named-checkzone {{ item|reverse_lookup_zone }} %s"
  with_items: bind_zone_networks
  notify: restart bind
  tags: bind

