# roles/bind/tasks/master.yml
# Set up a BIND master server
---

- name: Master | Main BIND config file (master)
  template:
    src: master_etc_named.conf.j2
    dest: "{{ bind_config }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: '0640'
    setype: named_conf_t
    validate: 'named-checkconf %s'
  notify: restart bind
  tags: bind

- name: Master | Create forward lookup zone file
  template:
    src: bind_zone.j2
    dest: "{{ bind_dir }}/{{ bind_zone_name }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "0640"
    setype: named_zone_t
    validate: 'named-checkzone -d {{ bind_zone_name }} %s'
  notify: restart bind
  tags: bind

- name: Master | Create reverse lookup zone file
  template:
    src: reverse_zone.j2
    dest: "{{ bind_dir }}/{{ item | ipaddr('revdns') | regex_replace('^(0+\\.)+', '') | regex_replace('\\.$', '') }}"
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: "0640"
    setype: named_zone_t
    #validate: "named-checkzone {{ item | ipaddr('revdns') | regex_replace('^(0+\\.)+', '') | regex_replace('\\.$', '') }} %s"
  with_items: "{{ bind_zone_networks }}"
  notify: restart bind
  tags: bind

